name: Format
on:
  push:
    branches:
      - master

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swift_format:
    name: swift-format
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app
      - name: Format
        run: make format
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run swift-format
          branch: 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
